title: Daniel Wong # your name (or website title) here
#logo: "/images/profile1.JPG width=50% height=50%" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst skilled in R, SQl, and geospatial tool QGIS
  <br><br>
  <a href="https://www.linkedin.com/in/wongjerngfoong">View My LinkedIn Profile</a> 
  
theme: minima
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
