title: Daniel Wong # your name (or website title) here
#logo: "/images/profile1.JPG width=50% height=50%" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst skilled in R, SQl, and geospatial tool QGIS
  <br><br>
  <a href="https://www.linkedin.com/in/wongjerngfoong">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

google_analytics: UA-000000-0 # your Google Analytics tracking ID here
